# Generated by Django 4.0.4 on 2022-05-29 14:50

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('decricao', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True, null=True, verbose_name='link')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_interesses)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_noticias)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('data', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_posts)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ano_realizacao', models.IntegerField()),
                ('resumo', models.TextField()),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('gitHub', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('relatorio', models.URLField(blank=True, null=True, verbose_name='Relatório')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_tfc)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='portfolio.pessoa')),
                ('orientador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orentador', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('decricao', models.CharField(max_length=2000)),
                ('acronimo', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True, verbose_name='Site Oficial')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_tecnologias)),
                ('criador', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=portfolio.models.resolution_path_projects)),
                ('participantes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('ano_letivo', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=500)),
                ('ects', models.IntegerField(default='6')),
                ('ranking', models.IntegerField(default='5')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente_teorica', to='portfolio.pessoa')),
                ('docentes_pratica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docente_pratica', to='portfolio.pessoa')),
                ('projetos', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.projeto')),
            ],
        ),
    ]
